# -*- coding: utf-8 -*-
"""wykres_multibar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHUlJtqiz1VWOmUJ2FMpB1nyo5DX58Ll
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
from cycler import cycler

#przygotowanie danych
osoby = ("Anna","Piotr","Olga","Roman")
informacje = {
    'wiek':(34,56,23,45),
    'waga':(56.8,89.6,60.3,105.6),
    'wzrost':(162,172,170,189)
}

x = np.arange(len(osoby))
width = 0.25
multiplier = 0

fig,ax = plt.subplots(constrained_layout=True)
for attribute,mesurement in informacje.items():
    offset = width*multiplier
    rects = ax.bar(x+offset,mesurement,width,label=attribute)
    ax.bar_label(rects,padding=5)
    multiplier += 1

ax.set_ylabel('cecha')
ax.set_title('wybrane informacje na temat osób')
ax.set_xticks(x+width,osoby)
ax.legend(loc='upper left', ncols=3)
ax.set_ylim(0,200)
plt.show()

plt.savefig("wykresmulti.jpg",dpi=300)